---
name: Integration Test

on:  # yamllint disable-line rule:truthy
    push:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    # set V to 2 when re-running jobs with debug logging enabled
    # see https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging
    V: "${{ secrets.ACTIONS_STEP_DEBUG && '2' }}"

jobs:
    systemd-storagetm:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-24.04
        timeout-minutes: 20
        concurrency:
            group: extended-systemd-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container:
                    - arch:latest
                    - fedora:latest
                    - gentoo:latest
                    - opensuse:latest
                    - ubuntu:rolling
                test:
                    - "73"
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}-amd
            options: '--device=/dev/kvm --device=/dev/nvme-fabrics --privileged'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v4
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: ./test/test-container.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
